pipeline:
  test:
    image: node:6
    commands:
      - npm install --color > npm-install.log
      - npm version
  debug:
    image: dryclean/drone-debug
    commands:
      - echo -e $PLUGIN_GIT_ID
      - echo -e $PLUGIN_GIT_PRIVATE
  install-cat:
    image: busybox
    commands:
      - cat npm-install.log

